### PR TITLE
Fix path error filename contains #

### PR DESCRIPTION
**Pull request by Mailkov**
@moollaza 

example file name: "/share/goodie/guitar_chords/999/G%23minor6.png"

you can try it on my PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1879

### CODE REVIEW

**Comment by Mailkov** [comment]
@moollaza 
If I must use a filename that contains `#` char I replace it with `%23` usually

example:
`"/share/goodie/guitar_chords/999/G#minor6.png"` replaces with `"/share/goodie/guitar_chords/999/G%23minor6.png"`

When I used this code on a Goodie (you can see it on my PR https://github.com/duckduckgo/zeroclickinfo-goodies/pull/1879) 
the duckpan gave me an error:
```
Error open (<) on 
'/home/codio/workspace/zeroclickinfo-goodies/share/goodie/guitar_chords/G#minor6.pngG%23minor6.png': 
No such file or directory at 
/home/codio/perl5/perls/perl-5.18.2/lib/site_perl/5.18.2/App/DuckPAN/Web.pm line 125.
```
As you can see the resulted file name is `G#minor6.pngG%23minor6.png` wrongly 
so I fixed this error ... now is  `G#minor6.png`

**Comment by moollaza** [comment]
@Mailkov thanks for explaining.

I spent a few minutes trying to understand my own code :frowning:  but I figured it out and the problems:

- We need to compare the reminder to the filename to ensure they're different
- We need to uri-unescape the filename

Here's how the code should look:

```perl
$share_dir = $_;
# Get filename from path and url unescape
my $filename = uri_unescape( pop @path_parts );
# Trim path from left to right to find parent dir of filename
# e.g /share/goodie/foo/foo_imgs/image.png -> "foo_imgs"
my $remainder = $request->path_info;
$remainder =~ s|$share_dir||;
$remainder =~ s|$filename||;
$remainder =~ s|//|/|;
$remainder =~ s|^/\d{3,4}||;

# if valid remainder exists, prepend to filename
$filename = "$remainder$filename" if $remainder ne $filename;
```

**Comment by Mailkov** [comment]
@moollaza 
I think is more correct that you make the PR to fix this bug
and close this PR!

**Comment by moollaza** [comment]
@Mailkov this LGTM :+1:

**Pull request merged**
