### PR TITLE
DuckPAN::Web support for Spice POST

### PR DESCRIPTION
**Pull request by jbarrett**
This should allow `duckpan server` to handle the changes in https://github.com/duckduckgo/duckduckgo/pull/204 - Rudimentary POST support for Spice.

If a Spice `post_body` is defined and we are NOT using a DDG endpoint (in the case of missing API keys in the environment or such), issue a POST request with this body.

Cc: @russellholt @MariagraziaAlastra @moollaza

### CODE REVIEW

**Comment by jbarrett** [comment]
Sorry for that **terrible** typo :flushed:

**Comment by GuiltyDolphin** [comment]
@jbarrett Have you been working on a new tool or something? :wink:

**Comment by jbarrett** [comment]
Is there currently a testing approach for `Server`

**Comment by zachthompson** [comment]
@jbarrett Not really. Mostly a "is it still working?" approach.

**Comment by zachthompson** [comment]
Thank you.

**Pull request merged**
