### PR TITLE
Correct 'error' exit codes

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
@zachthompson Instead of using '-1' (isn't that what C programmers do?) for exit
codes, use '1' to signal failure. From the docs itself: 'The only
Universally recognized values for {exit code} are 0 for success and 1
for error'.

### CODE REVIEW

**Comment by zachthompson** [comment]
Have to make sure we are checking codes correctly elsewhere.

**Comment by GuiltyDolphin** [comment]
@zachthompson You mean in DuckPAN? All the codes are used for is the final exit in [emit_and_exit](https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN.pm#L367). I just checked with `exit -1`, and (at least on my term) that becomes the exit code `255`.

**Comment by zachthompson** [comment]
@GuiltyDolphin No, I mean internally.  We use duckpan to install distributions in various places and I'll need to audit them to make sure they aren't checking for `-1` explicitly.

**Comment by GuiltyDolphin** [comment]
@zachthompson M'kay!

**Comment by zachthompson** [comment]
Thank you.

**Pull request merged**
