### PR TITLE
Updating Local Install instructions

### PR DESCRIPTION
**Pull request by moollaza**
Added steps to install Duckpan.org packages and fix any SSL issues.

Two users recently ran into issues and these were the steps I told them to follow which solved their problems.

/cc @zachthompson @talsraviv 

/cc @xaviervalarino

### CODE REVIEW

**Comment by moollaza** [comment]
@zachthompson additionally I think we may want to cleanup and update the install.pl script to use `--mirror ...` and it looks like we no longer need to have users install `Crypt::SSLeay` according to https://metacpan.org/pod/Crypt::SSLeay#DO-YOU-NEED-Crypt::SSLeay

**Comment by zachthompson** [comment]
Yeah, looks like you've started on install.pl.  Thank you.

**Comment by talsraviv** [comment]
@moollaza this is for local dev environments right not codio?

**Comment by moollaza** [comment]
Yup

**Pull request merged**
