### PR TITLE
Add notice about Node & Handlebars.js requirements

### PR DESCRIPTION
**Pull request by moollaza**
Also, small fix to Codio image position.

/cc @zachthompson

### CODE REVIEW

**Comment by zachthompson** [comment]
@moollaza We should only need handlebars when running dzil in an IA repo.  Is the average duckpan user going to be doing this?

**Comment by moollaza** [comment]
@zachthompson I think you'll need all the new dependencies if/when you try to run `duckpan test` -- I'm not sure how many devs actually use that vs `prove -Ili t/filename.t` though.

Maybe we should detect if they don't have those deps installed when they run something which needs them and give a message explainng what's needed? or we can refer them to these docs -- I can move these instructions to an "optional dependencies" section of sorts?

**Comment by zachthompson** [comment]
An optional dependencies section would probably be more accurate.  Hopefully running things like test and release externally is rare. I like the "less is more" approach with respect to dependencies.

**Comment by moollaza** [comment]
>I like the "less is more" approach with respect to dependencies.

100% with you on that!

**Comment by moollaza** [comment]
@zachthompson I've changed things a bit, added an optional dependencies section which explains what's required and where it's required (i.e. dzil build/install/test)

**Comment by moollaza** [comment]
In case someone runs into problems we can at least reference this.

**Comment by zachthompson** [comment]
Looks good :+1:

**Pull request merged**
