### PR TITLE
Style update

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Style wasn't entirely consistent throughout project, I've updated some of the aspects to be more in-line with other DDG projects.

* Some files were using spaces for indentation - some were using tabs.

### CODE REVIEW

**Comment by moollaza** [comment]
@GuiltyDolphin just spoke with @zachthompson -- we're both Tabs fans ;)

Let's keep this repo to tabs. Also, this commit would kinda ruin `git blame` which I'd like to avoid.

**Comment by moollaza** [comment]
I'm happy with killing trailing spaces though, and moving any spaces -> tabs

**Comment by GuiltyDolphin** [comment]
@moollaza Alright, I'll just revert the first and change spaces to tabs, no worries.

**Comment by moollaza** [comment]
@GuiltyDolphin thanks a lot! Much appreciated :+1:

**Comment by GuiltyDolphin** [comment]
@moollaza 29 files used tabs, 25 used spaces, tabs wins... marginally ;)

**Comment by moollaza** [comment]
@GuiltyDolphin looks like there's some conflicts now that we've merged your other PR. Please fix and then I'll be happy to merge.

I'm _shocked_ that there were 25 files with tabs. I must have let my guard down :eyes:  :guardsman:

**Comment by GuiltyDolphin** [comment]
@moollaza Done.

**Comment by moollaza** [comment]
@GuiltyDolphin Thanks! This LGTM :+1:

**Pull request merged**
