### PR TITLE
Add 'debug' flag as an alias for 'verbose'

### PR DESCRIPTION
**Pull request by GuiltyDolphin**
Fixes part of duckduckgo/p5-app-duckpan#222 as we can now use '--debug'
as a flag.

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@zachthompson I'm finished with this, anything to add?

**Comment by zachthompson** [comment]
Haven't had a chance to look at this really.  Looks like you changed a bit more than adding an alias ;)  Are you saying that all of these changed were necessary to support `--debug`?

**Comment by GuiltyDolphin** [comment]
@zachthompson Heh, sorry, here's what I've done:

- Added a role for commands that support verbose. 

- Replaced standard warn/die with use of Carp.

**Comment by GuiltyDolphin** [comment]
I've got some plans for Option::Tell in the future, but for now it allows switching of verbose/debug on any command.

**Comment by zachthompson** [comment]
@GuiltyDolphin This is too big of a change for a simple alias.,

**Comment by GuiltyDolphin** [comment]
@zachthompson Hehe, I'm not very good at naming these PRs :wink:

How about I pull the changes out into a couple of PRs? One for *just* the alias, one for the carp update, and either another for the per-command debug or have that with the first?

**Pull request closed without merging**
