### PR TITLE
Remove all admin functionality

### PR DESCRIPTION
**Pull request by zachthompson**
Commands:

* release
* setup
* poupload

Most of these were just wrappers around dzil.

### CODE REVIEW

**Comment by GuiltyDolphin** [comment]
@preemeijer Did you say you were using the `poupload` command?

**Comment by jbarrett** [comment]
Nobody uses `poupload` but me :)

(I know because it emails me each time).

Happy for it to be removed here - it's just a HTTP POST and trivially replaced.

**Comment by moollaza** [comment]
This LGTM :+1:

**Comment by preemeijer** [comment]
@GuiltyDolphin sorry for this late reaction... but no

**Pull request merged**
