### PR TITLE
* Add missing 'use strict; use warnings;' line

### PR DESCRIPTION
**Pull request by Manwar**
Hi,

I propose fix to CPANTS warning regarding missing 'use strict; use warnings;' line.

Please review it.
Many Thanks.

Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by moollaza** [comment]
@Manwar thanks, it looks like they suggest we add it to `Cmd::Query`, `Cmd::Release` and `Cmd::Test` as well?

http://cpants.cpanauthors.org/dist/App-DuckPAN/errors

**Comment by moollaza** [comment]
Actually, I just realized we're not using it anywhere...

**Comment by Manwar** [comment]
In my humble opinion, where ever MooX is imported, you don't need 'use strict; use warnings;' as MooX imports Moo which brings in these checks.

**Comment by moollaza** [comment]
> In my humble opinion, where ever MooX is imported, you don't need 'use strict; use warnings;' as MooX imports Moo which brings in these checks.

Ah, well then I guess your fix covers everything.

Let's add `no warnings 'uninitialized';` and then this should be good to merge.

**Comment by Manwar** [comment]
Where do you suggest, we should add "no warnings 'uninitialized'"?

**Comment by zachthompson** [comment]
@Manwar The problem with allowing moox to do this behind the scenes is, if/when we remove it or use something else, we almost certainly won't remember to add strict/warnings.  Doesn't hurt to have them redundantly specified afaik.

**Comment by Manwar** [comment]
@zachthompson I agree with you.

**Comment by zachthompson** [comment]
Thanks, we'll get the others later.

**Pull request merged**
